name: hello-world

on:
  # push:
  #   branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  repository_dispatch:
    types: [run-cypress-tests]

jobs:
  my-job-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    strategy:
      matrix:
        node-version: [22.3.0]
    
    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          
      - name: Install Cypress
        run: |
          npm ci
          npx cypress install

      - name: Run Cypress Tests
        run: npx cypress run
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: results
          path: ./cypress/results/
          retention-days: 30

      - name: Download Playwright Report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report

      - name: Show Playwright Report
        run: |
          echo "Playwright Report Contents:"
          ls -R ./playwright-report/
          # You can also add commands to process the report or display specific contents
