name: Cypress Tests

on:
  repository_dispatch:
    types: [run-cypress-tests]

jobs:
  my-job-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Playwright Report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Cypress
        run: |
          npm ci
          npx cypress install

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Show Playwright Report
        run: |
          echo "Playwright Report Contents:"
          ls -R ./playwright-report/
          # You can also add commands to process the report or display specific contents
