name: hello-world

on:
  # push:
  #   branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  my-job-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    strategy:
      matrix:
        node-version: [22.3.0]
    
    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          
      - name: Install Cypress
        run: |
          npm ci
          npx cypress install

      - name: Run Cypress Tests
        run: npx cypress run
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: results
          path: ./cypress/results/
          retention-days: 30
